language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t noratsm/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test -- --coverage

after_sucess:
  - docker build -t noratsm/multi-client ./client
  - docker build -t noratsm/multi-nginx ./nginx
  - docker build -t noratsm/multi-server ./server
  - docker build -t noratsm/multi-worker ./worker

# Log into the docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images
- docker pushv